name: Version Test
  # You may pin to the exact commit or the version.
  # uses: kzrnm/get-net-sdk-project-versions-action@7d65d2220244fd5275f2de24c018b18805bdaef1
on: [push, workflow_dispatch]

jobs:
  dotnet-build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: kzrnm/get-net-sdk-project-versions-action@v1.3.0
        with:
          proj-path: Oasis.ReportTestTool.csproj
      - run: echo "${{steps.get-version.outputs.version}}"
