name: Do stuff
on: [push, workflow_dispatch]

jobs:
  DoStuff:
    name: Do Stuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: get_version
        uses: greenygh0st/net-proj-release-version@v1
        with:
          
          # Filepath of the *.csproj file, relative to root of repository
          PROJ_FILE: Oasis.ReportTestTool/Oasis.ReportTestTool.csproj

      - name: Next Step
        run: echo "${{ steps.get_version.outputs.RELEASE_VERSION }}"
